$(document).ready(function(){
    $("header").hover(function(){
        $("header").css("cursor","pointer");
    });
    $(".choice1").click(function(){
        window.location.href="page4_ch1.html";
    });
    $(".choice2").click(function(){
        window.location.href="page4_ch2.html";
    });
});